# Generated by Django 3.2.3 on 2021-05-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
