version: '3.7'
services:
  web:
    image: nastiona00slastiona/project_mem:memlife
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./memlife/:/usr/src/memlife/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres_data: