version: '3.7'
services:
    web:
        image: nastiona00slastiona/project_mem_prod:latest
        command: gunicorn memlife.wsgi:application --bind 0.0.0.0:8000 --reload
        volumes:
            - static_volume:/usr/src/memlife/web/static
            - media_volume:/usr/src/memlife/web/media 
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        env_file:
        - ./.env.prod.db
    nginx:
        image: nastiona00slastiona/project_mem_nginx:latest
        volumes:
            - static_volume:/usr/src/memlife/web/static
            - media_volume:/usr/src/memlife/web/media 
        ports:
            - 1337:80
        depends_on:
            - web
volumes:
  postgres_data:
  static_volume:
  media_volume: