name: CI

on:
  push:
    branches: master

jobs:

  build:
    name: building and pushing
    runs-on: ubuntu-latest
  
    steps:
      - name: Checout repo
        uses: actions/checkout@main
        
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Building of image and running tests
        run: |
          docker build ./django_project_lab/memlife -t nastiona00slastiona/project_mem_prod:latest -f ./django_project_lab/memlife/Dockerfile.prod
          docker build ./django_project_lab/nginx -t nastiona00slastiona/project_mem_nginx:latest -f ./django_project_lab/nginx/Dockerfile
          docker-compose -f ./django_project_lab/docker-compose.prod.yml up -d 
          docker exec django_project_web python -m pytest
          docker-compose -f ./django_project_lab/docker-compose.prod.yml down
         
          
     
          
      - name: Pushing to docker
        run: |
          docker push nastiona00slastiona/project_mem_prod:latest
          docker push nastiona00slastiona/project_mem_nginx:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-push-image
      steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Reload Project
        run: gcloud compute ssh ariaignis_dragon@djangoproject --zone=europe-central2-a --command="sudo docker-compose -f app/Programming_instruments_and_tools/django_project_lab/docker-compose.prod.yml up -d"
        
