name: CI

on:
  push:
    branches: master

jobs:

  build:
    name: building and pushing
    runs-on: ubuntu-latest
  
    steps:
      - name: checout repo
        uses: actions/checkout@main
        
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: building of image and running tests
        run: |
          docker build ./django_project_lab/memlife -t nastiona00slastiona/project_mem_prod:latest -f ./django_project_lab/memlife/Dockerfile.prod
          docker build ./django_project_lab/nginx -t nastiona00slastiona/project_mem_nginx:latest -f ./django_project_lab/nginx/Dockerfile
         
          
     
          
      - name: pushing to docker
        run: |
          docker push nastiona00slastiona/project_mem_prod:latest
          docker push nastiona00slastiona/project_mem_nginx:latest
        
        
